name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3 with versioning
        run: |
          aws s3 sync . s3://madcportfoliobucket --delete

      - name: Get the latest css/style.css version ID
        id: get-style-version
        run: |
          VERSION_ID=$(aws s3api list-object-versions \
            --bucket madcportfoliobucket \
            --prefix css/style.css \
            --query 'sort_by(Versions, &LastModified)[-1].VersionId' \
            --output text)
          echo "VERSION_ID=${VERSION_ID}" >> $GITHUB_ENV

      - name: Verify Version ID Output
        run: |
          echo "Retrieved Version ID: $VERSION_ID"

      - name: Update HTML with css/style.css version ID
        run: |
          sed -i "s|css/style.css.*|css/style.css?versionId=$VERSION_ID|" portfolio.html
          aws s3 cp portfolio.html s3://madcportfoliobucket/portfolio.html